spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
server:
  port: 8081
security:
  jwt:
    secret: aW9nZmRhaGl1cmdoYWVpd2Z2bndlZnF3Y21vZWZtcXdlZm1xY3dlZmp3ZXJxZ2hucmd1YmRnZmJha3NkamdiaWVydWdmYmFlYmdha2pkZmc=
    access: 360000
    refresh: 2592000000
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
springdoc:
  override-with-generic-response: false
